# This file is generated by .github/workflows/release.yml on tag push.
# Manual edits will be overwritten on the next release.
class Qt < Formula
  desc "Translate Russian into clear, natural, polished business English"
  homepage "https://github.com/fred01/quick-translate"
  version "1.1.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/fred01/quick-translate/releases/download/v1.1.0/qt-darwin-arm64.tar.gz"
      sha256 "ce72a97618162a67464f41751ed41d810d5690dce766238c19e4199937f8b2c1"
    end
    on_intel do
      url "https://github.com/fred01/quick-translate/releases/download/v1.1.0/qt-darwin-amd64.tar.gz"
      sha256 "ceeba1f501dedd259e610758eb9bb8bd0b413924d8b6cd0607650d98e5ce3cab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fred01/quick-translate/releases/download/v1.1.0/qt-linux-arm64.tar.gz"
      sha256 "df8afeea9107b01a000f9e917f104382a086e98492d9b86abe292cd656954abe"
    end
    on_intel do
      url "https://github.com/fred01/quick-translate/releases/download/v1.1.0/qt-linux-amd64.tar.gz"
      sha256 "b4cb2010aeaf7224fe24715edfbd7b3893932c2fb1a04dd362015b132a061bf4"
    end
  end

  def install
    bin.install "qt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/qt version")
  end
end
