# This file is generated by .github/workflows/release.yml on tag push.
# Manual edits will be overwritten on the next release.
class Qt < Formula
  desc "Translate Russian into clear, natural, polished business English"
  homepage "https://github.com/fred01/quick-translate"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/fred01/quick-translate/releases/download/v1.0.0/qt-darwin-arm64.tar.gz"
      sha256 "30a6229296ebfed5c6f4827fe495890fc0a422aaf1b784a1ce7a56094e51e5f8"
    end
    on_intel do
      url "https://github.com/fred01/quick-translate/releases/download/v1.0.0/qt-darwin-amd64.tar.gz"
      sha256 "7e909b714681fc806b63e4c3deda4db78fff38a1c79ca456fcd3eef9edc155b2"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fred01/quick-translate/releases/download/v1.0.0/qt-linux-arm64.tar.gz"
      sha256 "85fdca228e44bc1a27829be18d31cefd30c75fc2b6772cf732da482105761d70"
    end
    on_intel do
      url "https://github.com/fred01/quick-translate/releases/download/v1.0.0/qt-linux-amd64.tar.gz"
      sha256 "e86489d7e48fd6d3b4aeeea8a5d90420b10a8687537c648eefb9c67485c008cf"
    end
  end

  def install
    bin.install "qt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/qt version")
  end
end
